name: Continuous Integration

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Version
      run: rustc --version
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Version
      run: rustc --version
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  macOS:
    name: macOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Version
      run: rustc --version
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
