name: Continuous Integration

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Version
      run: rustc --version
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
